apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-messaging
      version: green  # Unique label to distinguish green version
  template:
    metadata:
      labels:
        app: django-messaging
        version: green  # Label to identify the green version
    spec:
      containers:
      - name: django-messaging
        image: <your-docker-image>:green  # Replace with the new version image tag
        ports:
        - containerPort: 8080
